### ISSUE TITLE
Version in Window Title

### ISSUE THREAD

**Issue by gps137** [UHAXM1/Quantum#3]
I've used the program for five minutes and I love it already. I originally installed 1.0.0.0, then noticed a 1.0.1.0 available, tried to update using the right-click context-menu but noticed the version number didn't change in the menu title, then uninstalled/reinstalled the app from a fresh download and still see v1.0.0.0 displayed. I could be wrong, but I think the winform title needs to be updated to reflect the new version.
![CaptureTitle](https://github.com/user-attachments/assets/2c357d5e-2675-4d5d-b501-373581927818)

Overall, bravo!

**Comment by UHAXM1** [comment]
Hi, I have fixed this issue. Also note that pressing 'Update Now' does not update the program itself but forces the port to be updated right away, I have changed the wording in the latest version. 1.2 is now available.
