### ISSUE TITLE
App keeps popping up when alt-tabbing

### ISSUE THREAD

**Issue by drjedd** [UHAXM1/Quantum#4]
Hello, and thanks for your work first of all :)

I'm on Windows 11 using quantum 1.2 (latest afaik)
(I did have both previous releases installed prior so not a clean install)

I don't know how to reproduce this issue consistently yet, but a few times a day when I alt-tab between programs, Quantum shows up as one of them, despite having minimized the program because it's set up and I basically want it to run as a background task and forget about it.

I don't know if anyone else is experiencing similar issue. I will try to identify factors like key presses or other programs interfering. Or maybe I should try a clean install?

Thanks, all the best.

jedd

**Comment by UHAXM1** [comment]
Version 1.3.0.0 is now available, this should fix the window showing when alt-tabbing.

**Comment by drjedd** [comment]
The problem hasn't happen since so I guess it is solved indeed.
I'm curious as to what was the culprit? 👀

**Comment by UHAXM1** [comment]
The issue was the program was not closing the window correctly when Quantum first started, after you clicked the x to close the window it worked fine. So it was just a hidden on startup bug.
