### ISSUE TITLE
No valid port information found in logs

### ISSUE THREAD

**Issue by luverdark** [UHAXM1/Quantum#5]
Thank you for making this software.

When I first downloaded it, it was working fine, but now has stopped working. I have just downloaded the latest version and still have the same problem.

"No valid port information found in logs"

Checking my log file location there is 2 files.

service-logs.txt
service-logs.1.txt

Quantum is at it's default settings, its currently viewing the service-logs.txt file

Quantum has connected to qbitorrent just fine.

**Comment by UHAXM1** [comment]
Can you please email me the log files? My email address is 'null'

**Comment by luverdark** [comment]
The proton log file or does Quantum have one?

**Comment by UHAXM1** [comment]
The ProtonVPN log files

**Comment by luverdark** [comment]
Sent. Thank you

**Comment by UHAXM1** [comment]
Ok iv had a look at the log files, If I point my Quantum (version 1.4.0.0) to the log files it does find the port number, so the issue must be its reading from the wrong location, you can manually set the log file location, locate your ProtonVPN install point Quantum at it, it should be something like this "C:\Program Files\Proton\VPN\v3.3.2\ServiceData\Logs"
Please note the version, as it is possible to have left over log files from a previous version, if this is the case Quantum does not look for the new updated path (I will fix this in a future version).

On my machine I have both
C:\Program Files\Proton\VPN\v3.3.0\
and
C:\Program Files\Proton\VPN\v3.3.2\
I need to point Quantum at the newer path (3.3.2)

Try correcting the path and see if that gets it working.

**Comment by luverdark** [comment]
I replaced the path and now it is working. Thank you. I think it was still looking at the old version v3.3.0, whilst I have 3.3.2 installed.

**Comment by UHAXM1** [comment]
I will make it a point to patch this in the next version so it cannot happen again.
