### ISSUE TITLE
Unable to open / run on Windows 11

### ISSUE THREAD

**Issue by antonz44** [UHAXM1/Quantum#6]
On downloading the installer and running it on Windows 11, nothing happens whatsoever for me. 

I've checked for icons in the taskbar but there's nothing there and it's not blocked by antivirus either (tried disabled). 
I have installed the latest .NET desktop runtime from [here](https://dotnet.microsoft.com/en-us/download/dotnet/8.0). 

I have the same issue attempting to run the portable .exe rather than the installer. 

Running as admin also seems to do nothing, I don't get a UAC up even

Am I still missing something? Do I need to clone the repository or the linked submodule qBittorrent-net-client? I assume not as they'd be included with the installer?

**Comment by UHAXM1** [comment]
Quantum does not need admin permissions to run. Just to clarify, when you run the installer, it does show you the install sheild and it installs correctly? It also makes you a desktop shortcut to Quantum?

You could also try this

Go to Control Panel > Administrative Tools > Event Viewer.

Look for Application Logs under Windows Logs. Errors here can often give details about what's failing (like missing DLLs or permission issues).

However, based on what you have said, it sounds like something is blocking the app, what anti virus program do you use?

**Comment by antonz44** [comment]
Hi mate

No, even on attempting to run the installer, nothing happens. There is no install shield or installation taking place nor any desktop shortcut.

I use AVG antivirus free but I have tried disabling that and it seems to make no difference.

In event viewer, the relevant event being triggered on running either the installer or the portable .exe appears to be 5961 "Activation for Microsoft.Windows.Apprep.ChxApp_cw5n1h2txyewy!App failed. Error code: Class not registered. Activation phase: No phase defined"

Thanks!

**Comment by UHAXM1** [comment]
Based on what you have said and the error you are getting, i think something is fundamentally broken in your Wndows install.

Try the following

Open a command prompt as administrator

Type in "sfc /scannow" and press enter, this will check Windows for errors. Once it's complete reboot your system.

Then try to run the installer again.

If it still fails, I would try reinstalling any Visual Studio runtime libraries you have installed.

**Comment by antonz44** [comment]
Thanks!

Indeed this was a Windows issue which I was able to resolve by reinstalling Windows from installation media (whilst preserving all installed apps and files, so relatively pain free).

Appreciate your help on this, it is working perfectly for me now.
